>.<

Title: Find the average of inspections scores between 91 and 100
Link: https://platform.stratascratch.com/coding/9707-find-the-average-of-inspections-scores-between-91-and-100?code_type=2
Level: Easy

Find the mean of inspections scores between 91 and 100.
Assuming that the scores are normally distributed.

Data los_angeles_restaurant_health_inspections:
serial_number: text
activity_date: datetime
facility_name: text
score: bigint
grade: text
service_code: bigint
service_description: text
employee_id: text
facility_address: text
facility_city: text
facility_id: text
facility_state: text
facility_zip: text
owner_id: text
owner_name: text
pe_description: text
program_element_pe: bigint
program_name: text
program_status: text
record_id: text

>.<

Solution:

# Import your libraries
import pandas as pd

# Start writing code

los_angeles = pd.DataFrame(los_angeles_restaurant_health_inspections)

los_angeles_facility = los_angeles.groupby('facility_name')['score'].mean().reset_index()

los_angeles_score = los_angeles_facility[(los_angeles_facility['score']>91) & (los_angeles_facility['score']<100)]

los_angeles_score['facility_name']
    
Output:

facility_name
MARGARITAS CAFE
LAS MOLENDERAS
SANDRA'S TAMALES
CAFE GRATITUDE
INTI PERUVIAN RESTAURANT
WOLFGANG PUCK EXPRESS
IN N OUT DAILY MARKET
CHOI'S MARKET
LENTO MARKET LLC
PRINCIPIO MERCADO Y CARNICERIA
EL POLLO LOCO #3301
MARISCOS SAN MIGUEL ARCANGEL
PLAYA DORA
PLAN CHECK
LOCALI
KIM HUNG BAKERY
VINCENTE FOODS-MARKET
GWEN
OAXACALIFORNIA
MICHELLE'S DONUT HOUSE
LA PRINCESITA MARKET
ONO HAWAIIAN BBQ
FOOD 4 LESS #766
CAFE SEOUL NANDARANG
FRATERNAL ORDER OF EAGLES
ADMIRALS CLUB
SALLY'S SNACK SHOP
B SWEET DESSERT BAR
NORTHGATE MARKETS #38
SPARE TIRE
CJ COFFEE SHOP
OLEEGO
MAGEE'S KITCHEN
JACK IN THE BOX #3377
CARNITAS URUAPAN - MARKET & BAKERY
NUEVO JALISCO BAR
TACO HOUSE
TACOS EL UNICO
EDENDALE
MARIE CALLENDER'S RESTAURANT
EVO KITCHEN
GUISADOS
FLORES DISCOUNT MARKET
CONCERT HALL CAFE
KELLY'S COFFEE
RALPHS MARKET #759
THE OPRHEUM THEATRE
JONS MARKET
SAN MARCOS TORTILLERIA
MIKE'S DELI #2
KIM'S MANNA FISH & CHIP, INC
RENAISSANCE 96TH STREET BISTRO
EMMANUEL MINI MARKET
DAILY DONUT
KIM CHUY RESTAURANT
CHIPOTLE  MEXICAN GRILL
NOODLES TIME
LUCKY STATION
THE COFFEE BEAN & TEA LEAF
OASISTKOS
LA CONVENTION CENTER
OCEAN GROCERY MARKET
AMIGOS
EXCELLENT THAI CAFE
LORENA PHARMACY
LAGUNA MARKET - MEAT DEPT.
SWEETGREEN
BYBLOS
ALL ABOUT THE BREAD
SANCHEZ MEAT MARKET
BACO MERCAT
ALI HASAN
ORLEANS ANS YORKS FINE DELI
LA ESPERANZA BAKERY
OLYMPIC COLLECTION BUFFET
MR BOBA
DONUT FACTORY
CUSTOM HOTEL
MARCE MINI MART
SHAKEYS PIZZA PARLOR #1
PACE
OK MARKET
STIR CRAZY COFFEE HOUSE
KIKKA @ WHOLE FOODS WESTWOOD
YUM YUM DONUTS #9235 STORAGE
BLOCK PARTY
FIX COFFEE
CHEVRON 55944
EDIBLE ARRANGEMENTS - 250
CINEMARK
THE CARVING BOARD
EL RANCHON
STONE BAKERY/MARKET
GREEN HOUSE
LUPE'S LUNCH ROOM RESTAURANT
SKY BAR
USC GALEN CENTER
DODGER STADIUM
PAT & LORRAINEIS COFFEE SHOP
THE VEGGIE GRILL
CHUY'S MARKET
WATTS COFFEE HOUSE
DENNY'S RESTAURANT #2125
IN-N-OUT BURGER #119
MCCALL'S MEAT & FISH CO
SSCM MARKET
DON PEDRO'S PALENQUE
IMPERIAL CHOPSTICKS
PAILIN THAI CUISINE
FLORENCE GAS MART INC
LITTLE ETHIOPIA RESTAURANT
YOSHINOYA #1219
CANTER'S DELI
FLAME BROILER TRBK #80
ICHIBAN OF TOKYO
DEL REY LIQUOR
FIVE STAR CHINESE FOOD
SOUPLANTATION
LUPE'S TACO STAND
EL RINCON DE LAS DELICIAS
FRANKLIN 76
99 CENTS ONLY STORE #0375
MOJO
TAVERN
PHORAGE
HARRIS MARKET
WESTIN LAKEVIEW BISTRO
STREET CHURROS
HABITAT COFFEE SHOP
STARBUCKS COFFEE
GUATEMALTECA BAKERY
BIBIGO-REMOTE STORAGE
PICK-UP STIX
FOOD AND BOUNTY
UMAMI BURGER
LEMONADE
STARBUCKS EVENING
FLOR BLANCA
ROLLING STONE SPACE 7C
SUNSET EXPRESS
VANILLA BAKESHOP
THE KITCHEN COUNTER
EL CEMITERO PLOBLANO
LAS PALMITAS FRUIT #4
DURANGO RESTAURANT
FOOD HAUS CAFE
NATIONAL BAKING CO
SAMOSA HOUSE
PA ORD NOODLE
MARISCOS EL DIABLO
KLATCH COFFEE
SAKURA RESTAURANT WAREHOUSE
LOS POBLANOS RESTAURANTE
DENNY'S RESTAURANT #7757
PANDA CHINESE RESTAURANT
ELYSIAN RESTAURANT
CANCUN RESTAURANT
NENA RESTAURANT
B.L. RESTAURANT
LA FUENTE RESTAURANT
LOS ARCOS RESTAURANT
LEONARDO'S RESTAURANT
TEXIS RESTAURANT AND ENTERTAINMENT
D'LIDO RESTAURANT AND BAKERY
EARLES RESTAURANT
QWENCH 9TH AND FLOWER
MORI SUSHI
ANTONIO'S
QWENCH JUICE BAR
DRINK / QUENCH HOLLYWOOD
TAMALES ALBERTO
ROBEKS JUICE
DRINK COFFEE + TEA
PRESTO DELI
