>.<

Title: Find all routine inspections where high-risk issues were found
Link: https://platform.stratascratch.com/coding/9690-find-all-routine-inspections-where-high-risk-issues-were-found?code_type=2
Level: Easy

Find all routine inspections where high-risks issues were found.

Data los_angeles_restaurant_health_inspections:
serial_number: text
activity_date: datetime
facility_name: text
score: bigint
grade: text
service_code: bigint
service_description: text
employee_id: text
facility_address: text
facility_city: text
facility_id: text
facility_state: text
facility_zip: text
owner_id: text
owner_name: text
pe_description: text
program_element_pe: bigint
program_name: text
program_status: text
record_id: text

>.<

Solution:

# Import your libraries
import pandas as pd

# Start writing code
los_angeles_restaurant = pd.DataFrame(los_angeles_restaurant_health_inspections)

los_angeles_restaurant_filter = los_angeles_restaurant[(los_angeles_restaurant['pe_description'].str.contains('HIGH RISK',na=False)) & los_angeles_restaurant['service_description'].str.contains('ROUTINE INSPECTION',na=False)]['facility_name'].drop_duplicates()
    
Output:

facility_name
MARGARITAS CAFE
LAS MOLENDERAS
CAFE GRATITUDE
THE WAFFLE
INTI PERUVIAN RESTAURANT
WOLFGANG PUCK EXPRESS
SOPITA RAMEN
PRINCIPIO MERCADO Y CARNICERIA
EL POLLO LOCO #3301
MARISCOS SAN MIGUEL ARCANGEL
PLAYA DORA
PLAN CHECK
GWEN
LA PRINCESITA MARKET
ONO HAWAIIAN BBQ
FOOD 4 LESS #766
CAFE SEOUL NANDARANG
CHA CHA CHILI
SPARE TIRE
CJ COFFEE SHOP
OLEEGO
MAGEE'S KITCHEN
CARNITAS URUAPAN - MARKET & BAKERY
TACO HOUSE
TACOS EL UNICO
EDENDALE
MARIE CALLENDER'S RESTAURANT
WA SSADA ON DAL JAPANESE RES
EVO KITCHEN
GUISADOS
ANTOJITOS LISETH
RALPHS MARKET #759
JONS MARKET
SAN MARCOS TORTILLERIA
KIM'S MANNA FISH & CHIP, INC
RENAISSANCE 96TH STREET BISTRO
KIM CHUY RESTAURANT
CHIPOTLE  MEXICAN GRILL
NOODLES TIME
OASISTKOS
LA CONVENTION CENTER
EXCELLENT THAI CAFE
GUI IL BUNJI
LAGUNA MARKET - MEAT DEPT.
SWEETGREEN
SIMPLE
BYBLOS
SANCHEZ MEAT MARKET
BACO MERCAT
JINSOL GUKBAP
ORLEANS ANS YORKS FINE DELI
OLYMPIC COLLECTION BUFFET
YEN SUSHI & SAKE BAR
STK/BAGATELLE
RICKS DRIVE IN & OUT
CUSTOM HOTEL
OO KOOK KOREAN BBQ STORAGE
RESTAURANT AFSHAN CLASSIS
SHAKEYS PIZZA PARLOR #1
KIKKA @ WHOLE FOODS WESTWOOD
MAMA HONG'S VIETNAMESE KITCHEN
POPEYE DUMPLING AND NOODLES
LOUIS JUNIOR
SUPERIOR GROCERS #113
THE CARVING BOARD
STONE BAKERY/MARKET
LUPE'S LUNCH ROOM RESTAURANT
PAT & LORRAINEIS COFFEE SHOP
THE VEGGIE GRILL
TRIPLE 8 RESTAURANT
WATTS COFFEE HOUSE
DENNY'S RESTAURANT #2125
MCCALL'S MEAT & FISH CO
SSCM MARKET
CAVA MEZZE GRILL
DON PEDRO'S PALENQUE
IMPERIAL CHOPSTICKS
PAILIN THAI CUISINE
LITTLE ETHIOPIA RESTAURANT
CANTER'S DELI
FLAME BROILER TRBK #80
ICHIBAN OF TOKYO
FIVE STAR CHINESE FOOD
SOUPLANTATION
LUPE'S TACO STAND
EL RINCON DE LAS DELICIAS
CARNICERIA LA OAXAQUENA
TAVERN
DON LENCHO
PHORAGE
HARRIS MARKET
WESTIN LAKEVIEW BISTRO
ISLAND PACIFIC SUPERMARKET
LATINO MARKET
FOOD AND BOUNTY
CALIFORNIA MEXICAN GRILL
UMAMI BURGER
RANCHO ZAPOTILLO ( MEAT MARK
KAJU UDON
CHINESE HOUSE HAOCHI
THE TALPA
ROLLING STONE SPACE 7C
SUNSET EXPRESS
THE KITCHEN COUNTER
PANDA EXPRESS
EL DIABLO ANTOJITOS MEXICANOS
EL CEMITERO PLOBLANO
NAM WON GOL
CHAYA SUSHI
LAS PALMITAS FRUIT #4
DURANGO RESTAURANT
FOOD HAUS CAFE
SLAUSON FISH MARKET
SAMOSA HOUSE
PA ORD NOODLE
A B C EXPRESS
AUTENTICO SABOR CASERO
TACOS GALAN
MARISCOS EL DIABLO
HABIBI CAFE & LOUNGE
LOS POBLANOS RESTAURANTE
DENNY'S RESTAURANT #7757
PANDA CHINESE RESTAURANT
ELYSIAN RESTAURANT
NENA RESTAURANT
B.L. RESTAURANT
LA FUENTE RESTAURANT
LOS ARCOS RESTAURANT
LEONARDO'S RESTAURANT
TEXIS RESTAURANT AND ENTERTAINMENT
EARLES RESTAURANT
MORI SUSHI
PUPUSERIA Y RESTAURANTE SIHUATEHUACAN
ANTONIO'S
TAMALES ALBERTO
